"""empty message

Revision ID: 4e81cb6cf038
Revises: 9899b7a38c40
Create Date: 2026-04-15 19:16:36.592813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e81cb6cf038'
down_revision: Union[str, Sequence[str], None] = '9899b7a38c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('medium', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('specific_location', sa.String(length=500), nullable=True),
    sa.Column('crime_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scraped_article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_news_id'), 'crime_news', ['id'], unique=False)
    op.create_table('scraped_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_scraped_articles_article_id'), 'scraped_articles', ['article_id'], unique=True)
    op.create_index(op.f('ix_scraped_articles_id'), 'scraped_articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_articles_id'), table_name='scraped_articles')
    op.drop_index(op.f('ix_scraped_articles_article_id'), table_name='scraped_articles')
    op.drop_table('scraped_articles')
    op.drop_index(op.f('ix_crime_news_id'), table_name='crime_news')
    op.drop_table('crime_news')
    # ### end Alembic commands ###
